# Generated by Django 3.2.5 on 2021-12-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'ordering': ('-create_time',), 'verbose_name': '资源链接', 'verbose_name_plural': '资源链接'},
        ),
    ]
