# Generated by Django 3.2.5 on 2021-12-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0002_alter_resources_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='url2',
            field=models.FileField(default='', upload_to='resources/', verbose_name='下载链接2'),
        ),
    ]
