# Generated by Django 3.2.5 on 2021-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0004_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='cover',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
