# Generated by Django 3.2.5 on 2021-12-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0005_articlepost_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='cover',
        ),
    ]
