# Generated by Django 3.2.5 on 2021-12-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0008_alter_articlepost_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='avatar',
        ),
    ]
