# Generated by Django 3.2.5 on 2021-12-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0010_articlepost_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
