# Generated by Django 3.2.5 on 2021-12-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0011_alter_articlepost_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='avatar',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='avatar2',
            field=models.ImageField(blank=True, upload_to='article2/%Y%m%d/'),
        ),
    ]
