# Generated by Django 3.2.5 on 2021-12-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0012_auto_20211227_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar2',
            field=models.FileField(blank=True, upload_to='article2/%Y%m%d/'),
        ),
    ]
