# Generated by Django 3.2.5 on 2021-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0013_alter_articlepost_avatar2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='avatar2',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='avatar_img',
            field=models.ImageField(blank=True, upload_to='article_img/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='avatar_svg',
            field=models.FileField(blank=True, upload_to='article_svg/%Y%m%d/'),
        ),
    ]
