# Generated by Django 3.2.5 on 2021-12-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0014_auto_20211227_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='avatar_img',
        ),
    ]
