# Generated by Django 3.2.5 on 2021-12-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='critic',
            field=models.CharField(default='A', max_length=100),
        ),
    ]
